### ISSUE TITLE
try issue

### ISSUE THREAD

**Issue by cheesepastaa** [cheesepastaa/animated-funicular#2]
change `int n = 89;
		if ((n & 1) == 0) {
			System.out.println("Even");
		} else {
			System.out.println("Odd");
		}`
to
``int n = 89;
		if ((n & 1) == 0) {
			System.out.println("Even");
		} else {
			System.out.println("Odd");
		}``

**Comment by sam2611** [comment]
plz assign me this issue.

**Comment by cheesepastaa** [comment]
the work is done
